
import { Question } from '../types';

export const fullQuestionBank: Question[] = [
  // Original 64 questions with references
  { id: 1, type: '1B', question: '(一)耶穌的比喻中，浪子回頭後，父親給他穿上什麼、戴上什麼、穿上什麼？', answer: '袍子、戒指、鞋', reference: '路加福音 15:22' },
  { id: 2, type: '1B', question: '(一)舊約中以智慧著稱的君王是誰？', answer: '所羅門', reference: '列王紀上 3:12' },
  { id: 3, type: '2B', question: '(二)「道成了肉身，住在我們中間，充充滿滿地有恩典有真理。」這節經文出自新約哪卷書？', answer: '約翰福音', reference: '約翰福音 1:14' },
  { id: 4, type: '1B', question: '(一)摩西的哥哥，也是以色列第一位大祭司是誰？', answer: '亞倫', reference: '出埃及記 28:1' },
  { id: 5, type: '3B', question: '(三)尼希米帶領以色列人返回耶路撒冷，主要進行了哪項重建工作？', answer: '重建耶路撒冷城牆', reference: '尼希米記 2:17' },
  { id: 6, type: '1B', question: '(一)「你們的光也當這樣照在人前…」這段教導出自耶穌的哪篇講道？', answer: '登山寶訓', reference: '馬太福音 5:16' },
  { id: 7, type: '2B', question: '(二)舊約時代，哪兩位探子對進入迦南地充滿信心，並最終得以進入？', answer: '約書亞和迦勒', reference: '民數記 14:30' },
  { id: 8, type: 'HR', question: '(全)但以理書中，尼布甲尼撒王夢見一個巨像，這個像的頭、胸膛/膀臂、肚腹/腰、腿，分別是用什麼材質製成的？', answer: '金、銀、銅、鐵', reference: '但以理書 2:32-33' },
  { id: 9, type: '1B', question: '(一)新約中被稱為「愛的使徒」的是誰？', answer: '約翰', reference: '約翰一書 4:7-8' },
  { id: 10, type: '2B', question: '(二)亞伯拉罕因信被稱為義，他獻上以撒的地點是哪座山？', answer: '摩利亞山', reference: '創世記 22:2' },
  { id: 11, type: '1B', question: '(一)士師記中，哪位士師的力量來源與他的頭髮有關？', answer: '參孫', reference: '士師記 16:17' },
  { id: 12, type: '3B', question: '(三)保羅書信中，哪一類被稱為「監獄書信」？請列舉其中兩卷。', answer: '以弗所書、腓立比書、歌羅西書、腓利門書 (任選二)', reference: '弗3:1, 腓1:7, 西4:18, 門1' },
  { id: 13, type: '2B', question: '(二)耶穌在客西馬尼園禱告時，特別帶了哪三位門徒同去？', answer: '彼得、雅各、約翰', reference: '馬太福音 26:37' },
  { id: 14, type: '1B', question: '(一)大衛王在成為國王前，以什麼武器戰勝了巨人歌利亞？', answer: '甩石的機弦', reference: '撒母耳記上 17:49-50' },
  { id: 15, type: 'HR', question: '(全)根據加拉太書，聖靈所結的果子有九種表現，除了仁愛、喜樂、和平之外，請再說出三種。', answer: '忍耐、恩慈、良善、信實、溫柔、節制 (任選三)', reference: '加拉太書 5:22-23' },
  { id: 16, type: '1B', question: '(一)耶穌所行的神蹟中，祂曾使管會堂的誰的女兒從死裡復活？', answer: '睚魯', reference: '馬可福音 5:41-42' },
  { id: 17, type: '2B', question: '(二)舊約中，哪位先知在魚腹中禱告三日三夜？', answer: '約拿', reference: '約拿書 1:17' },
  { id: 18, type: 'HR', question: '(全)人若不是從(　　)生的，就不能進神的國，此乃指(　　)和(　　)。', answer: '水和聖靈、洗禮、受聖靈', reference: '約翰福音 3:5' },
  { id: 19, type: '1B', question: '(一)耶穌潔淨聖殿時，推翻了誰的桌子和誰的凳子？', answer: '兌換銀錢之人和賣鴿子之人的', reference: '馬太福音 21:12' },
  { id: 20, type: '1B', question: '(一)聖經中的第一位殺人犯是誰？', answer: '該隱', reference: '創世記 4:8' },
  { id: 21, type: '2B', question: '(二)以利亞先知在哪座山上挑戰巴力的四百五十個先知並得勝？', answer: '迦密山', reference: '列王紀上 18:20-40' },
  { id: 22, type: 'HR', question: '(全)為何我們不奉父、子、聖靈的名施洗，而要奉主耶穌的名施洗？', answer: '因父、子、聖靈都不是名，其名乃是耶穌。' },
  { id: 23, type: '1B', question: '(一)新約中，哪位稅吏長為了看耶穌而爬上了桑樹？', answer: '撒該', reference: '路加福音 19:4' },
  { id: 24, type: '3B', question: '(三)耶利米哀歌主要是為哪座城市的毀滅而作的哀歌？', answer: '耶路撒冷', reference: '耶利米哀歌 (全書)' },
  { id: 25, type: '1B', question: '(一)主禱文中，「免我們的債」的下一句是什麼？', answer: '如同我們免了人的債', reference: '馬太福音 6:12' },
  { id: 26, type: '2B', question: '(二)哪位君王因驕傲自大，被神懲罰，像牛一樣吃草七年？', answer: '尼布甲尼撒', reference: '但以理書 4:33' },
  { id: 27, type: '1B', question: '(一)保羅在前往哪座城市的途中，被耶穌的大光光照而悔改信主？', answer: '大馬士革 (大馬色)', reference: '使徒行傳 9:3-6' },
  { id: 28, type: '3B', question: '(三)舊約聖經分為哪五大部分？', answer: '摩西五經、歷史書、智慧書(詩歌)、大先知書、小先知書', reference: '聖經概述' },
  { id: 29, type: '1B', question: '(一)耶穌復活後，向哪位多疑的門徒顯現，並讓他觸摸其傷口？', answer: '多馬', reference: '約翰福音 20:27-28' },
  { id: 30, type: '2B', question: '(二)使徒行傳記載，教會歷史上第一位為主殉道的人是誰？', answer: '司提反', reference: '使徒行傳 7:59-60' },
  { id: 31, type: '1B', question: '(一)箴言中多次提到，「敬畏耶和華」是智慧的什麼？', answer: '開端', reference: '箴言 9:10' },
  { id: 32, type: 'HR', question: '(全)耶穌在登山寶訓中宣告了「八福」。除了「虛心的人有福了」，請再說出另外兩福。', answer: '哀慟的人、溫柔的人、飢渴慕義的人、憐恤人的人、清心的人、使人和睦的人、為義受逼迫的人 (任選二)', reference: '馬太福音 5:3-12' },
  { id: 33, type: '1B', question: '(一)哪位門徒在耶穌被捕後，曾三次不認主？', answer: '彼得', reference: '馬太福音 26:69-75' },
  { id: 34, type: '2B', question: '(二)但以理的三個朋友是誰？他們因拒絕拜金像被扔進了火窯。', answer: '沙得拉、米煞、亞伯尼歌', reference: '但以理書 3章' },
  { id: 35, type: '1B', question: '(一)耶穌升天前，頒布給門徒的最後一個命令被稱為什麼？', answer: '大使命', reference: '馬太福音 28:19-20' },
  { id: 36, type: '3B', question: '(三)舊約律法規定了三大節期，所有男丁每年要上耶路撒冷朝聖。是哪三個節期？', answer: '逾越節、五旬節、住棚節', reference: '出埃及記 23:14-17' },
  { id: 37, type: '2B', question: '(二)保羅說出「我靠著那加給我力量的，凡事都能做」這句名言是在哪一卷書？', answer: '腓立比書', reference: '腓立比書 4:13' },
  { id: 38, type: '1B', question: '(一)舊約中，誰的妻子因為回頭看被毀滅的所多瑪城而變成了一根鹽柱？', answer: '羅得', reference: '創世記 19:26' },
  { id: 39, type: 'HR', question: '(全)新約哪一卷書信沒有明確作者，主要論證耶穌基督超越舊約的眾先知、天使和祭司制度？', answer: '希伯來書', reference: '希伯來書 (全書)' },
  { id: 40, type: '1B', question: '(一)五旬節聖靈降臨時，門徒們被聖靈充滿，開始說起什麼？', answer: '別國的話 (方言)', reference: '使徒行傳 2:4' },
  { id: 41, type: '2B', question: '(二)哪位士師帶領三百人，用號角、空瓶和火把擊敗了米甸大軍？', answer: '基甸', reference: '士師記 7章' },
  { id: 42, type: '1B', question: '(一)保羅寫給提摩太和提多的書信，通常被歸類為哪一類書信？', answer: '教牧書信', reference: '提摩太前後書、提多書' },
  { id: 43, type: '3B', question: '(三)耶穌的撒種比喻中，撒在好土裡的種子代表哪種人？', answer: '聽了道，持守在誠實善良的心裡，並且忍耐著結實的人。', reference: '路加福音 8:15' },
  { id: 44, type: '1B', question: '(一)以撒的妻子是誰？', answer: '利百加', reference: '創世記 24:67' },
  { id: 45, type: '2B', question: '(二)哪位先知曾預言將有出於耶西的本的「和平的君」的降生？', answer: '以賽亞', reference: '以賽亞書 11:1' },
  { id: 46, type: '1B', question: '(一)新約中，哪一卷書被認為是保羅神學的巔峰之作？', answer: '羅馬書', reference: '羅馬書 (全書)' },
  { id: 47, type: 'HR', question: '(全)哥林多前書第15章集中討論了基督教信仰中一個極其重要的核心教義，是什麼？', answer: '基督的復活與信徒的復活', reference: '哥林多前書 15章' },
  { id: 48, type: '1B', question: '(一)大衛王最好的朋友是誰？他也是掃羅王的兒子。', answer: '約拿單', reference: '撒母耳記上 18:1-4' },
  { id: 50, type: '1B', question: '(一)聖經中記載的最長的一章是哪一章？', answer: '詩篇119篇', reference: '詩篇 119篇' },
  { id: 51, type: '3B', question: '(三)以西結書第一章的異象中，四個活物各有四個臉，分別是什麼形象？', answer: '人、獅子、牛、鷹', reference: '以西結書 1:10' },
  { id: 52, type: '1B', question: '(一)神吩咐挪亞，每樣潔淨的活物要帶幾對上方舟？', answer: '七對', reference: '創世記 7:2' },
  { id: 53, type: '2B', question: '(二)雅各在伯特利夢見一個梯子立在地上，有什麼在梯子上上去下來？', answer: '神的使者', reference: '創世記 28:12' },
  { id: 54, type: 'HR', question: '(全)舊約哪本書卷記載以色列人出埃及後，在曠野漂流並進行兩次人口普查？', answer: '民數記', reference: '民數記 (全書)' },
  { id: 55, type: '1B', question: '(一)亞當和夏娃被逐出伊甸園後，神派了什麼來看守生命樹的道路？', answer: '基路伯和四面轉動發火焰的劍', reference: '創世記 3:24' },
  { id: 56, type: '3B', question: '(三)保羅身上有一根「刺」，他三次求主，主的回應是什麼？', answer: '我的恩典夠你用的，因為我的能力是在人的軟弱上顯得完全。', reference: '哥林多後書 12:7-9' },
  { id: 57, type: '1B', question: '(一)神應許亞伯拉罕，他的後裔要像天上的什麼、海邊的什麼那樣多？', answer: '星、沙', reference: '創世記 22:17' },
  { id: 58, type: '2B', question: '(二)摩西在西奈山上領受十誡時，山下的以色列百姓拜了什麼偶像？', answer: '金牛犢', reference: '出埃及記 32章' },
  { id: 59, type: '1B', question: '(一)耶穌的第一個神蹟是將水變成酒，這個神蹟發生在什麼場合？', answer: '迦拿的婚宴', reference: '約翰福音 2:1-11' },
  { id: 60, 'type': '3B', question: '(三)哪位先知書的結尾，是神與先知關於一棵蓖麻樹的對話，藉以彰顯神的憐憫？', answer: '約拿書', reference: '約拿書 4:6-11' },
  { id: 61, type: '1B', question: '(一)以色列人過約旦河進入迦南地時，抬著什麼走在最前面，使河水斷流？', answer: '約櫃', reference: '約書亞記 3:13-17' },
  { id: 62, type: '2B', question: '(二)路得記中，波阿斯是路得的什麼人，因此有權利娶她並贖回產業？', answer: '至近的親屬', reference: '路得記 2:20' },
  { id: 63, type: '1B', question: '(一)十誡的第一誡是什麼？', answer: '除了我以外，你不可有別的神。', reference: '出埃及記 20:3' },
  { id: 64, type: 'HR', question: '(全)約翰福音記載了耶穌的七個「我是」的宣告，除了「我是世界的光」，請再說出另外兩個。', answer: '生命的糧、門、好牧人、復活和生命、道路/真理/生命、真葡萄樹 (任選二)', reference: '約翰福音 6:35, 8:12, 10:9, 10:11, 11:25, 14:6, 15:1' },
  
  // New questions with references
  { id: 66, type: '1B', question: '(一)馬太福音中，東方博士拜見嬰孩耶穌時，獻上哪三樣禮物？', answer: '黃金、乳香、沒藥', reference: '馬太福音 2:11' },
  { id: 68, type: '1B', question: '(一)耶穌說：「我就是道路、真理、____。」', answer: '生命', reference: '約翰福音 14:6' },
  { id: 69, type: '3B', question: '(三)請說出挪亞三個兒子的名字。', answer: '閃、含、雅弗', reference: '創世記 6:10' },
  { id: 70, type: '1B', question: '(一)誰是雅各最愛的妻子？', answer: '拉結', reference: '創世記 29:30' },
  { id: 71, type: '2B', question: '(二)耶穌在曠野禁食禱告幾天後，受到魔鬼的試探？', answer: '四十天', reference: '馬太福音 4:2' },
  { id: 72, type: 'HR', question: '(全)啟示錄中描述的新耶路撒冷城有幾個門？門是用什麼造的？街道是用什麼造的？', answer: '十二個門、珍珠、精金', reference: '啟示錄 21:12, 21' },
  { id: 73, type: '1B', question: '(一)耶利哥城倒塌前，以色列人每天繞城幾次？', answer: '一次', reference: '約書亞記 6:3' },
  { id: 74, type: '2B', question: '(二)哪位先知膏立了大衛作以色列的王？', answer: '撒母耳', reference: '撒母耳記上 16:13' },
  { id: 75, type: '1B', question: '(一)「你們要先求他的國和他的義」，下一句是什麼？', answer: '這些東西都要加給你們了', reference: '馬太福音 6:33' },
  { id: 76, type: '3B', question: '(三)以色列國分裂後，北國以色列的首都是哪裡？南國猶大的首都是哪裡？', answer: '撒馬利亞、耶路撒冷', reference: '列王紀上 16:24' },
  { id: 77, type: '2B', question: '(二)耶穌使拉撒路復活前，他已經死了幾天？', answer: '四天', reference: '約翰福音 11:39' },
  { id: 78, type: '1B', question: '(一)哪位先知被稱為「流淚的先知」？', answer: '耶利米', reference: '耶利米書 9:1' },
  { id: 79, type: 'HR', question: '(全)請解釋「以馬內利」這個名字的意思，並說明它出自舊約哪卷書的預言？', answer: '神與我們同在，出自以賽亞書', reference: '以賽亞書 7:14, 馬太福音 1:23' },
  { id: 80, type: '1B', question: '(一)在耶穌的比喻中，哪種人把房子蓋在磐石上？', answer: '聽見主的話就去行的人', reference: '馬太福音 7:24' },
  { id: 81, type: '2B', question: '(二)保羅的宣教旅程中，第一位在歐洲信主的人是誰？', answer: '呂底亞', reference: '使徒行傳 16:14' },
  { id: 82, type: '3B', question: '(三)舊約中，哪位女子為了拯救本族同胞，冒著生命危險去見波斯王？', answer: '以斯帖', reference: '以斯帖記 4:16' },
  { id: 83, type: '1B', question: '(一)耶穌用五餅二魚餵飽了多少人？', answer: '五千人 (不計婦女和孩子)', reference: '馬太福音 14:21' },
  { id: 84, type: '1B', question: '(一)聖經中最短的一卷書是哪一卷？', answer: '約翰二書', reference: '約翰二書' },
  { id: 85, type: '2B', question: '(二)神用什麼記號與挪亞立約，應許不再用洪水毀滅世界？', answer: '彩虹', reference: '創世記 9:13' },
  { id: 86, type: 'HR', question: '(全)根據腓立比書，保羅勸勉信徒要思想的事情有哪些特質？請列舉三樣。', answer: '凡是真實的、可敬的、公義的、清潔的、可愛的、有美名的、有德行的、值得稱讚的 (任選三)', reference: '腓立比書 4:8' },
  { id: 87, type: '1B', question: '(一)雅各與天使摔跤後，被改了什麼名字？', answer: '以色列', reference: '創世記 32:28' },
  { id: 88, type: '3B', question: '(三)新約聖經分為哪五大部分？', answer: '四福音書、歷史書(使徒行傳)、保羅書信、普通書信、預言書(啟示錄)', reference: '聖經概述' },
  { id: 89, type: '1B', question: '(一)「當孝敬父母」是十誡中的第幾誡？', answer: '第五誡', reference: '出埃及記 20:12' },
  { id: 90, type: '2B', question: '(二)哪位王后因拒絕在王的酒席上露面而被廢？', answer: '瓦實提', reference: '以斯帖記 1:12, 19' },
  { id: 93, type: '1B', question: '(一)「不可殺人」是十誡中的第幾誡？', answer: '第六誡', reference: '出埃及記 20:13' },
  { id: 94, type: '2B', question: '(二)使徒行傳中，保羅在哪個城市對當地人講論「未識之神」？', answer: '雅典', reference: '使徒行傳 17:23' },
  { id: 95, type: '1B', question: '(一)創世記中，神創造的第六天造了什麼？', answer: '陸地上的活物和人', reference: '創世記 1:24-27' },
  { id: 96, type: 'HR', question: '(全)根據哥林多前書第13章，「愛是」什麼？請說出愛的四種表現。', answer: '恆久忍耐、又有恩慈、不嫉妒、不自誇、不張狂、不做害羞的事、不求自己的益處、不輕易發怒、不計算人的惡、不喜歡不義、只喜歡真理 (任選四)', reference: '哥林多前書 13:4-7' },
  { id: 97, type: '1B', question: '(一)誰是施洗約翰的父親？', answer: '撒迦利亞', reference: '路加福音 1:13' },
  { id: 99, type: '1B', question: '(一)「人若賺得全世界，賠上自己的生命，有什麼益處呢？」這句話是誰說的？', answer: '耶穌', reference: '馬太福音 16:26' },
  { id: 100, type: '3B', question: '(三)十災中的前三災是什麼？', answer: '水變血、蛙災、虱災', reference: '出埃及記 7-8章' },
  { id: 101, type: '2B', question: '(二)耶穌教導門徒禱告時說：「我們在天上的父」，這段禱告被稱為什麼？', answer: '主禱文', reference: '馬太福音 6:9' },
  { id: 102, type: '1B', question: '(一)哪本書記錄了以色列人建造會幕的詳細過程？', answer: '出埃及記', reference: '出埃及記 35-40章' },
  { id: 103, type: 'HR', question: '(全)根據以弗所書第6章，神所賜的全副軍裝包括哪些部分？請列舉四樣。', answer: '真理的腰帶、公義的護心鏡、平安福音的鞋、信德的藤牌、救恩的頭盔、聖靈的宝劍 (任選四)', reference: '以弗所書 6:13-17' },
  { id: 104, type: '1B', question: '(一)大衛的兒子中，繼承他王位的是誰？', answer: '所羅門', reference: '列王紀上 1:30' },
  { id: 105, type: '2B', question: '(二)在路加福音的好撒馬利亞人比喻中，祭司和利未人都走過了，誰幫助了那位受傷的人？', answer: '一個撒馬利亞人', reference: '路加福音 10:33' },
  { id: 106, type: '1B', question: '(一)「神愛世人，甚至將他的獨生子賜給他們…」出自哪卷書？', answer: '約翰福音', reference: '約翰福音 3:16' },
  { id: 107, type: '3B', question: '(三)哪位先知娶了淫婦歌篾為妻，以象徵神對不忠的以色列的愛？', answer: '何西阿', reference: '何西阿書 1:2-3' },
  { id: 108, type: '1B', question: '(一)馬可福音的作者馬可，是哪位使徒的屬靈兒子？', answer: '彼得', reference: '彼得前書 5:13' },
  { id: 109, type: '2B', question: '(二)掃羅王死後，哪位元帥擁立掃羅的兒子伊施波設在瑪哈念作王，與大衛對抗？', answer: '押尼珥', reference: '撒母耳記下 2:8-9' },
  { id: 110, type: '1B', question: '(一)「凡勞苦擔重擔的人，可以到我這裡來…」是誰的邀請？', answer: '耶穌', reference: '馬太福音 11:28' },
  { id: 111, type: 'HR', question: '(全)啟示錄寫給亞細亞的七個教會，請說出其中三個教會的名字。', answer: '以弗所、士每拿、別迦摩、推雅推喇、撒狄、非拉鐵非、老底嘉 (任選三)', reference: '啟示錄 1:11' },
  { id: 112, type: '1B', question: '(一)以色列人出埃及時，神用什麼在日間和夜間引導他們？', answer: '日間雲柱，夜間火柱', reference: '出埃及記 13:21' },
  { id: 113, type: '2B', question: '(二)哪位先知奉神之命，對著骸骨的平原發預言，使骸骨復活成為大軍？', answer: '以西結', reference: '以西結書 37章' },
  { id: 114, type: '1B', question: '(一)誰是第一位看見耶穌復活的人？', answer: '抹大拉的馬利亞', reference: '約翰福音 20:16-18' },
  { id: 115, type: '3B', question: '(三)約書亞記中，妓女喇合因為幫助了以色列的探子，她和她的一家如何得救？', answer: '把一條朱紅線繩繫在窗戶上', reference: '約書亞記 2:18, 6:25' },
  { id: 116, type: '2B', question: '(二)耶穌的十二門徒中，哪一位是稅吏？', answer: '馬太 (利未)', reference: '馬太福音 9:9' },
  { id: 117, type: '1B', question: '(一)「貪財是萬惡之根」出自哪一卷書信？', answer: '提摩太前書', reference: '提摩太前書 6:10' },
  { id: 118, type: 'HR', question: '(全)耶穌在十字架上說了七句話，被稱為「十架七言」。請說出其中兩句。', answer: '「父啊，赦免他們！因為他們所做的，他們不曉得。」、「我實在告訴你，今日你要同我在樂園裡了。」、「母親，看，你的兒子！」、「我的神！我的神！為什麼離棄我？」、「我渴了。」、「成了！」、「父啊！我將我的靈魂交在你手裡。」(任選二)', reference: '福音書綜合' },
  { id: 119, type: '1B', question: '(一)哪位士師是左撇子，他用短劍刺殺了摩押王伊磯倫？', answer: '以笏', reference: '士師記 3:15-21' },
  { id: 120, type: '2B', question: '(二)腓利門書是保羅為誰寫的求情信？', answer: '阿尼西母', reference: '腓利門書 (全書)' },
  { id: 121, type: '1B', question: '(一)「不可作假見證陷害人」是十誡中的第幾誡？', answer: '第九誡', reference: '出埃及記 20:16' },
  { id: 124, type: '1B', question: '(一)耶穌教導說：「你們的義若不勝於文士和____的義，斷不能進天國。」', answer: '法利賽人', reference: '馬太福音 5:20' },
  { id: 125, type: 'HR', question: '(全)根據詩篇第一篇，怎樣的人便為有福？請描述這種人的三個特徵。', answer: '不從惡人的計謀、不站罪人的道路、不坐褻慢人的座位、喜愛耶和華的律法、晝夜思想 (任選三)', reference: '詩篇 1:1-3' },
  { id: 126, type: '1B', question: '(一)詩篇23篇中，「我雖然行過死蔭的幽谷，也不怕遭害，因為…」？', answer: '你與我同在', reference: '詩篇 23:4' },
  { id: 127, type: '2B', question: '(二)耶穌所講的「失羊的比喻」中，牧人有多少隻羊？他去找回幾隻？', answer: '一百隻，去找一隻', reference: '路加福音 15:4' },
  { id: 128, type: '1B', question: '(一)誰寫了聖經中的雅歌？', answer: '所羅門', reference: '雅歌 1:1' },
  { id: 129, type: '3B', question: '(三)亞哈王的妻子是誰？她慫恿以色列人拜巴力。', answer: '耶洗別', reference: '列王紀上 16:31' },
  { id: 130, type: '1B', question: '(一)「你們要彼此相愛，像我愛你們一樣」，這是耶穌給門徒的什麼命令？', answer: '新命令', reference: '約翰福音 13:34' },
  { id: 131, type: '2B', question: '(二)哪位先知被神稱為「人子」？', answer: '以西結', reference: '以西結書 2:1' },
  { id: 132, type: 'HR', question: '(全)創世記第一章記載了神的創造。請按順序列出神第一天到第三天創造了什麼？', answer: '第一天：光；第二天：空氣(天)；第三天：地、海、植物', reference: '創世記 1:3-13' },
  { id: 133, type: '1B', question: '(一)耶穌的家鄉是哪裡？', answer: '拿撒勒', reference: '馬太福音 2:23' },
  { id: 134, type: '2B', question: '(二)哪位女王曾遠道而來，要聽所羅門的智慧話？', answer: '示巴女王', reference: '列王紀上 10:1' },
  { id: 135, type: '1B', question: '(一)「你們祈求，就給你們；尋找，就尋見；叩門，就給你們開門。」這教導出自哪裡？', answer: '登山寶訓 (或 馬太福音/路加福音)', reference: '馬太福音 7:7' },
  { id: 136, type: '3B', question: '(三)彼得前書提到，信徒是「被揀選的族類」，也是什麼？請再說出另外兩個稱號。', answer: '君尊的祭司、聖潔的國度、屬神的子民', reference: '彼得前書 2:9' },
  { id: 137, type: '2B', question: '(二)在耶穌的比喻中，不饒恕人的惡僕人，欠了主人多少銀子？', answer: '一千萬銀子', reference: '馬太福音 18:24' },
  { id: 138, type: '1B', question: '(一)摩西的岳父是誰？', answer: '葉忒羅', reference: '出埃及記 3:1' },
  { id: 139, type: 'HR', question: '(全)希伯來書第11章被稱為「信心篇」，其中列舉了許多信心的偉人。請舉出三位。', answer: '亞伯、以諾、挪亞、亞伯拉罕、撒拉、以撒、雅各、約瑟、摩西、喇合、基甸、巴拉、參孫、耶弗他、大衛、撒母耳等 (任選三)', reference: '希伯來書 11章' },
  { id: 140, type: '1B', question: '(一)誰是賣主耶穌的門徒？', answer: '加略人猶大', reference: '馬太福音 26:14-16' },
  { id: 141, type: '2B', question: '(二)「萬事都互相效力，叫愛神的人得益處」這節經文出自哪卷書？', answer: '羅馬書', reference: '羅馬書 8:28' },
  { id: 142, type: '1B', question: '(一)「你要盡心、盡性、盡意，愛主你的神。」是誡命中的第幾條？', answer: '第一條 (最大的)', reference: '馬太福音 22:37-38' },
  { id: 143, type: '3B', question: '(三)巴別塔事件導致了什麼結果？', answer: '語言被變亂，人們分散到世界各地', reference: '創世記 11:7-9' },
  { id: 144, type: '2B', question: '(二)哪位先知宣告預言說：「必有童女懷孕生子，人要稱他的名為以馬內利」？', answer: '以賽亞', reference: '以賽亞書 7:14' },
  { id: 145, type: '1B', question: '(一)彼得在五旬節講道後，有多少人悔改受洗？', answer: '三千人', reference: '使徒行傳 2:41' },
  { id: 146, type: 'HR', question: '(全)聖餐的餅和杯分別預表耶穌的什麼？這個儀式是耶穌在哪個晚上設立的？', answer: '身體和血，逾越節的晚上(最後的晚餐)', reference: '馬太福音 26:26-28' },
  { id: 147, type: '1B', question: '(一)「施比受更為有福」這句話是誰說的？', answer: '主耶穌', reference: '使徒行傳 20:35' },
  { id: 148, type: '2B', question: '(二)哪位底馬暗中離棄保羅，往帖撒羅尼迦去了？', answer: '底馬', reference: '提摩太後書 4:10' },
  { id: 149, type: '1B', question: '(一)摩西頒布的十誡是在哪座山領受的？', answer: '西奈山 (何烈山)', reference: '出埃及記 19:20' },
  { id: 151, type: '1B', question: '(一)誰是約瑟和馬利亞在耶穌之後生的第一個兒子，也就是耶穌肉身的弟弟？', answer: '雅各', reference: '馬太福音 13:55' },
  { id: 152, type: '2B', question: '(二)但以理因為一天三次禱告感謝神，被扔進了什麼地方？', answer: '獅子坑', reference: '但以理書 6:10, 16' },
  { id: 153, type: '1B', question: '(一)耶穌稱誰為「磐石」，並說要在此磐石上建造教會？', answer: '彼得', reference: '馬太福音 16:18' },
  { id: 155, type: '1B', question: '(一)以掃為了喝什麼，將長子的名分賣給了雅各？', answer: '紅豆湯', reference: '創世記 25:33-34' },
  { id: 156, type: '2B', question: '(二)使徒行傳中，亞拿尼亞和他的妻子撒非喇因為欺哄誰而當場死亡？', answer: '聖靈 (或 彼得)', reference: '使徒行傳 5:1-10' },
  { id: 158, type: '3B', question: '(三)哪位王行耶和華眼中看為正的事，拆毀邱壇，廢掉偶像，並舉辦了一次盛大的逾越節，但最終因驕傲而死於與埃及王的戰爭中？', answer: '約西亞', reference: '列王紀下 22-23章' },
  { id: 159, type: '2B', question: '(二)「人心籌算自己的道路；惟耶和華指引他的腳步。」出自哪卷智慧書？', answer: '箴言', reference: '箴言 16:9' },
  { id: 160, type: '1B', question: '(一)「不可貪戀人的房屋」是十誡中的第幾誡？', answer: '第十誡', reference: '出埃及記 20:17' },
  { id: 162, type: '1B', question: '(一)在畢士大池邊，耶穌醫好了一個病了多久的人？', answer: '三十八年', reference: '約翰福音 5:5' },
  { id: 163, type: '2B', question: '(二)哪位先知曾用一根全新的腰帶比喻猶大和以色列的驕傲將被敗壞？', answer: '耶利米', reference: '耶利米書 13章' },
  { id: 164, type: '1B', question: '(一)誰是摩西的姐姐？', answer: '米利暗', reference: '出埃及記 15:20' },
  { id: 165, type: '3B', question: '(三)迦勒窺探迦南地時幾歲？最終得地為業時幾歲？', answer: '四十歲，八十五歲', reference: '約書亞記 14:7, 10' },
  { id: 166, type: '2B', question: '(二)保羅在哪次宣教旅程中，在路司得被誤認為是希臘神祇希耳米？', answer: '第一次', reference: '使徒行傳 14:8-12' },
  { id: 167, type: '1B', question: '(一)哪位是雅各用計騙取長子祝福的哥哥？', answer: '以掃', reference: '創世記 27章' },
  { id: 168, type: '3B', question: '(三)耶穌基督在升天前囑咐門徒要在(　　)等候所應許的聖靈。', answer: '耶路撒冷', reference: '使徒行傳 1:4' },
  { id: 169, type: '1B', question: '(一)耶穌說，好樹結好果子，壞樹結什麼？', answer: '壞果子', reference: '馬太福音 7:17' },
  { id: 170, type: '2B', question: '(二)舊約的最後一卷書是什麼？', answer: '瑪拉基書', reference: '瑪拉基書' },
  { id: 171, type: '3B', question: '(三)以色列民在男嬰出生第(　　)天為他施行割禮。', answer: '八', reference: '利未記 12:3' },
  { id: 172, type: '3B', question: '(三)哪位猶大王因為長大痲瘋，被隔離直到去世，由他兒子約坦管理國事？', answer: '烏西雅 (亞撒利雅)', reference: '歷代志下 26:16-21' },
  { id: 173, type: '2B', question: '(二)哪位是巴拿巴的表弟，曾一度離開保羅的宣教團隊，但後來又成為保羅得力的同工？', answer: '馬可', reference: '使徒行傳 15:37-39, 提摩太後書 4:11' },
  { id: 174, type: '1B', question: '(一)誰是第一位殉道的使徒？', answer: '雅各 (約翰的哥哥)', reference: '使徒行傳 12:2' },
  { id: 175, type: 'HR', question: '(全)利未記中規定了五種主要的祭，請說出其中三種。', answer: '燔祭、素祭、平安祭、贖罪祭、贖愆祭 (任選三)', reference: '利未記 1-7章' },
  { id: 176, type: '1B', question: '(一)誰接替摩西成為以色列人的領袖？', answer: '約書亞', reference: '申命記 34:9' },
  { id: 177, type: '2B', question: '(二)彼得在異象中聽見聲音說：「神所潔淨的，你不可當作俗物。」這聲音重複了幾次？', answer: '三次', reference: '使徒行傳 10:16' },
  { id: 178, type: '1B', question: '(一)傳道書說，「虛空的虛空」下一句是？', answer: '凡事都是虛空', reference: '傳道書 1:2' },
  { id: 180, type: '2B', question: '(二)在耶穌的比喻中，一個國王為兒子擺設婚宴，但被邀請的客人卻找藉口不來，於是國王派僕人去哪裡邀請人？', answer: '岔路口', reference: '馬太福音 22:8-9' },
  { id: 181, type: '1B', question: '(一)「不可偷盜」是十誡中的第幾誡？', answer: '第八誡', reference: '出埃及記 20:15' },
  { id: 182, type: 'HR', question: '(全)哈巴谷書中，先知與神有兩輪對話，最後他宣告：「雖然無花果樹不發旺…然而，我要因耶和華歡欣。」這段宣告表達了怎樣的信心？', answer: '超越環境的信心、單單以神為樂的信心', reference: '哈巴谷書 3:17-18' },
  { id: 183, type: '1B', question: '(一)耶穌出來傳道時大約幾歲？', answer: '三十歲', reference: '路加福音 3:23' },
  { id: 187, type: '2B', question: '(二)使徒行傳中，來自亞歷山大的亞波羅是個有學問、最能講解聖經的人，但誰給他更詳細地講解了神的道？', answer: '百基拉和亞居拉', reference: '使徒行傳 18:24-26' },
  { id: 188, type: '1B', question: '(一)創世記中，最長壽的人是誰？', answer: '瑪土撒拉', reference: '創世記 5:27' },
  { id: 189, type: 'HR', question: '(全)舊約中，神的約櫃裡放著三樣東西，是哪三樣？', answer: '盛嗎哪的金罐、亞倫發過芽的杖、兩塊約版', reference: '希伯來書 9:4' },
  { id: 190, type: '1B', question: '(一)耶穌說，天國好像什麼，藏在地裡？', answer: '寶貝', reference: '馬太福音 13:44' },
  { id: 191, type: '2B', question: '(二)哪位使徒被稱為「半尼其」，意思是「雷子」？', answer: '雅各和約翰', reference: '馬可福音 3:17' },
  { id: 192, type: '1B', question: '(一)哪位是底波拉時代的以色列軍隊元帥？', answer: '巴拉', reference: '士師記 4:6' },
  { id: 193, type: '3B', question: '(三)耶穌的「十個童女」比喻中，聰明的童女和愚拙的童女最大的區別是什麼？', answer: '聰明的預備了油在器皿裡', reference: '馬太福音 25:1-13' },
  { id: 195, type: '1B', question: '(一)「你們心裡不要憂愁，你們信神，也當信我。」這句話出自哪卷書？', answer: '約翰福音', reference: '約翰福音 14:1' },
  { id: 197, type: '1B', question: '(一)詩篇第一篇說，義人要像一棵什麼樹？', answer: '栽在溪水旁的樹', reference: '詩篇 1:3' },
  { id: 198, type: '2B', question: '(二)哪位使徒帶領埃提阿伯的太監信主並為他施洗？', answer: '腓利', reference: '使徒行傳 8:26-38' },
  { id: 199, type: '1B', question: '(一)大衛犯罪後，哪位先知去指責他？', answer: '拿單', reference: '撒母耳記下 12:1-7' },
  
  // TJC Doctrine Questions
  { id: 201, type: '2B', question: '(二) 本會的洗禮方式有哪三個重要的要素？', answer: '奉主耶穌聖名、全身入水、面向下', reference: '真耶穌教會基本信仰' },
  { id: 202, type: '1B', question: '(一) 耶穌設立洗腳禮的目的是什麼？', answer: '與主有分、彼此相愛、聖潔、謙卑、服事、饒恕', reference: '約翰福音 13:8, 14-15' },
  { id: 203, type: '2B', question: '(二) 聖餐禮所用的餅和杯，分別代表什麼？', answer: '主的身體和主的血', reference: '哥林多前書 11:23-26' },
  { id: 204, type: '1B', question: '(一) 根據本會信條，安息日是星期幾？', answer: '星期六 (週六)', reference: '創世記 2:2-3' },
  { id: 205, type: '3B', question: '(三) 根據本會信條，領受聖靈的主要外顯憑據是什麼？', answer: '說靈言 (身體會振動)', reference: '使徒行傳 2:4, 10:44-46' },
  { id: 206, type: 'HR', question: '(全) 十大信條中第二條提到，信耶穌是道成肉身的，祂為拯救罪人死在十字架上，第幾天復活升天？祂是人類唯一的救主，也是什麼和什麼？', answer: '第三天；天地的「主宰」、獨一的「真神」', reference: '真耶穌教會十大信條' }
];
